export default [
  {
    entityName: 'license',
    inverseEntityName: 'user',
    propertyName: 'user',
    joinColumnName: 'userId',
    joinPropertyName: 'user',
    relationHash: 'bGljZW5zZTp1c2VyOm9uZS10by1tYW55',
    joinColumnOne: false,
    joinColumnNullable: false,
    inverseJoinColumnNullable: false,
    inverseJoinColumnOne: true,
    relationType: 'many-to-one',
  },
  {
    entityName: 'user',
    inverseEntityName: 'license',
    propertyName: 'license',
    joinColumnName: 'userId',
    joinPropertyName: 'user',
    relationHash: 'bGljZW5zZTp1c2VyOm9uZS10by1tYW55',
    joinColumnOne: true,
    joinColumnNullable: true,
    inverseJoinColumnNullable: false,
    inverseJoinColumnOne: false,
    relationType: 'one-to-many',
  },
  {
    entityName: 'license',
    inverseEntityName: 'license_organization_organization',
    joinPropertyName: 'licenseId',
    joinColumnName: 'licenseId',
    joinColumnOne: true,
    joinColumnNullable: false,
    inverseJoinColumnOne: false,
    inverseJoinColumnNullable: false,
    relationType: 'one-to-many',
    relationHash: 'bGljZW5zZTpsaWNlbnNlX29yZ2FuaXphdGlvbl9vcmdhbml6YXRpb246b25lLXRvLW1hbnk=',
  },
  {
    entityName: 'license',
    inverseEntityName: 'organization',
    propertyName: 'organization',
    joinColumnName: 'license_organization_organization',
    joinPropertyName: 'licenseId',
    relationHash: 'bGljZW5zZTpvcmdhbml6YXRpb246bWFueS10by1tYW55',
    joinColumnOne: false,
    joinColumnNullable: false,
    inverseJoinColumnNullable: true,
    inverseJoinColumnOne: false,
    relationType: 'many-to-many',
  },
  {
    entityName: 'organization',
    inverseEntityName: 'license',
    propertyName: 'license',
    joinColumnName: 'license_organization_organization',
    joinPropertyName: 'licenseId',
    relationHash: 'bGljZW5zZTpvcmdhbml6YXRpb246bWFueS10by1tYW55',
    joinColumnOne: false,
    joinColumnNullable: true,
    inverseJoinColumnNullable: false,
    inverseJoinColumnOne: false,
    relationType: 'many-to-many',
  },
  {
    entityName: 'organization',
    inverseEntityName: 'license_organization_organization',
    joinPropertyName: 'organizationId',
    joinColumnName: 'organizationId',
    joinColumnOne: true,
    joinColumnNullable: false,
    inverseJoinColumnOne: false,
    inverseJoinColumnNullable: false,
    relationType: 'one-to-many',
    relationHash: 'bGljZW5zZV9vcmdhbml6YXRpb25fb3JnYW5pemF0aW9uOm9yZ2FuaXphdGlvbjpvbmUtdG8tbWFueQ==',
  },
  {
    entityName: 'user',
    inverseEntityName: 'photo',
    propertyName: 'photo',
    joinColumnName: 'photoId',
    joinPropertyName: 'photo',
    relationHash: 'cGhvdG86dXNlcjpvbmUtdG8tb25l',
    joinColumnOne: true,
    joinColumnNullable: true,
    inverseJoinColumnNullable: true,
    inverseJoinColumnOne: true,
    relationType: 'one-to-one',
  },
];
