export default [
  {
    entityName: 'user',
    propertyName: 'id',
    columnName: 'id',
    attributeKey: 'PK',
    columnType: 'number',
    columnTypeWithLength: 'number',
    comment: '',
  },
  {
    entityName: 'user',
    propertyName: 'firstName',
    columnName: 'first_name',
    attributeKey: '',
    columnType: 'string',
    columnTypeWithLength: 'string',
    comment: 'user firstname',
  },
  {
    entityName: 'user',
    propertyName: 'lastName',
    columnName: 'lastName',
    attributeKey: '',
    columnType: 'varchar',
    columnTypeWithLength: 'varchar(64)',
    comment: '',
  },
  {
    entityName: 'user',
    propertyName: 'isActive',
    columnName: 'isActive',
    attributeKey: '',
    columnType: 'boolean',
    columnTypeWithLength: 'boolean',
    comment: 'line1\nline2\nline3',
  },
  {
    entityName: 'user',
    propertyName: 'photo',
    columnName: 'photoId',
    attributeKey: 'FK',
    columnType: 'number',
    columnTypeWithLength: 'number',
    comment: '',
  },
];
