export default [
  {
    entityName: 'user',
    propertyName: 'id',
    columnName: 'id',
    attributeKey: 'PK',
    columnType: 'number',
    columnTypeWithLength: 'number',
    comment: '',
    weight: 20649017.22,
  },
  {
    entityName: 'user',
    propertyName: 'firstName',
    columnName: 'first_name',
    attributeKey: '',
    columnType: 'string',
    columnTypeWithLength: 'string',
    comment: 'user firstname',
    weight: 663020.17,
  },
  {
    entityName: 'user',
    propertyName: 'lastName',
    columnName: 'lastName',
    attributeKey: '',
    columnType: 'varchar',
    columnTypeWithLength: 'varchar(64)',
    comment: '',
    weight: 743014.25,
  },
  {
    entityName: 'user',
    propertyName: 'isActive',
    columnName: 'isActive',
    attributeKey: '',
    columnType: 'boolean',
    columnTypeWithLength: 'boolean',
    comment: 'line1\nline2\nline3',
    weight: 736017.07,
  },
  {
    entityName: 'user',
    propertyName: 'photo',
    columnName: 'photoId',
    attributeKey: 'FK',
    columnType: 'number',
    columnTypeWithLength: 'number',
    comment: '',
    weight: 10649010.18,
  },
];
