export default [
  {
    tableName: 'license',
    entityName: 'License',
    columns: [
      {
        entityName: 'license',
        propertyName: 'id',
        columnName: 'id',
        attributeKey: 'PK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
        isNullable: '',
        weight: 20649017.22,
      },
      {
        entityName: 'license',
        propertyName: 'user',
        columnName: 'userId',
        attributeKey: 'FK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
        isNullable: '',
        weight: 10649005.07,
      },
      {
        entityName: 'license',
        propertyName: 'description',
        columnName: 'description',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
        isNullable: '',
        weight: 663022.21,
      },
      {
        entityName: 'license',
        propertyName: 'title',
        columnName: 'title',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
        isNullable: '',
        weight: 663006.17,
      },
      {
        entityName: 'license',
        propertyName: 'expire',
        columnName: 'expire',
        attributeKey: '',
        columnType: 'date',
        columnTypeWithLength: 'date',
        comment: '',
        isNullable: '',
        weight: 414021.02,
      },
    ],
  },
  {
    tableName: 'license_organization_organization',
    entityName: 'license_organization_organization',
    columns: [
      {
        entityName: 'license_organization_organization',
        propertyName: 'licenseId',
        columnName: 'licenseId',
        attributeKey: 'FK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
        isNullable: '',
        weight: 10649014.17,
      },
      {
        entityName: 'license_organization_organization',
        propertyName: 'organizationId',
        columnName: 'organizationId',
        attributeKey: 'FK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
        isNullable: '',
        weight: 10649011.08,
      },
    ],
  },
  {
    tableName: 'organization',
    entityName: 'Organization',
    columns: [
      {
        entityName: 'organization',
        propertyName: 'id',
        columnName: 'id',
        attributeKey: 'PK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
        isNullable: '',
        weight: 20649017.22,
      },
      {
        entityName: 'organization',
        propertyName: 'description',
        columnName: 'description',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
        isNullable: '',
        weight: 663022.21,
      },
      {
        entityName: 'organization',
        propertyName: 'title',
        columnName: 'title',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
        isNullable: '',
        weight: 663006.17,
      },
      {
        entityName: 'organization',
        propertyName: 'expire',
        columnName: 'expire',
        attributeKey: '',
        columnType: 'date',
        columnTypeWithLength: 'date',
        comment: '',
        isNullable: '',
        weight: 414021.02,
      },
    ],
  },
  {
    tableName: 'photo',
    entityName: 'Photo',
    columns: [
      {
        entityName: 'photo',
        propertyName: 'id',
        columnName: 'id',
        attributeKey: 'PK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
        isNullable: '',
        weight: 20649017.22,
      },
      {
        entityName: 'photo',
        propertyName: 'description',
        columnName: 'description',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
        isNullable: '',
        weight: 663022.21,
      },
      {
        entityName: 'photo',
        propertyName: 'size',
        columnName: 'size',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
        isNullable: '',
        weight: 663007.17,
      },
      {
        entityName: 'photo',
        propertyName: 'title',
        columnName: 'title',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
        isNullable: '',
        weight: 663006.17,
      },
    ],
  },
  {
    tableName: 'user',
    entityName: 'User',
    columns: [
      {
        entityName: 'user',
        propertyName: 'id',
        columnName: 'id',
        attributeKey: 'PK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
        isNullable: '',
        weight: 20649017.22,
      },
      {
        entityName: 'user',
        propertyName: 'photo',
        columnName: 'photoId',
        attributeKey: 'FK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
        isNullable: 'nullable',
        weight: 10649010.18,
      },
      {
        entityName: 'user',
        propertyName: 'lastName',
        columnName: 'lastName',
        attributeKey: '',
        columnType: 'varchar',
        columnTypeWithLength: 'varchar(64)',
        comment: '',
        isNullable: '',
        weight: 743014.25,
      },
      {
        entityName: 'user',
        propertyName: 'isActive',
        columnName: 'isActive',
        attributeKey: '',
        columnType: 'boolean',
        columnTypeWithLength: 'boolean',
        comment: 'line1<br />line2<br />line3',
        isNullable: '',
        weight: 736017.07,
      },
      {
        entityName: 'user',
        propertyName: 'firstName',
        columnName: 'first_name',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: 'user firstname',
        isNullable: '',
        weight: 663020.17,
      },
    ],
  },
];
