export default [
  {
    tableName: 'license',
    entityName: 'License',
    columns: [
      {
        entityName: 'license',
        propertyName: 'id',
        columnName: 'id',
        attributeKey: 'PK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
      },
      {
        entityName: 'license',
        propertyName: 'title',
        columnName: 'title',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
      },
      {
        entityName: 'license',
        propertyName: 'description',
        columnName: 'description',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
      },
      {
        entityName: 'license',
        propertyName: 'expire',
        columnName: 'expire',
        attributeKey: '',
        columnType: 'date',
        columnTypeWithLength: 'date',
        comment: '',
      },
      {
        entityName: 'license',
        propertyName: 'user',
        columnName: 'userId',
        attributeKey: 'FK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
      },
    ],
  },
  {
    tableName: 'license_organization_organization',
    entityName: 'license_organization_organization',
    columns: [
      {
        entityName: 'license_organization_organization',
        propertyName: 'licenseId',
        columnName: 'licenseId',
        attributeKey: 'FK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
      },
      {
        entityName: 'license_organization_organization',
        propertyName: 'organizationId',
        columnName: 'organizationId',
        attributeKey: 'FK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
      },
    ],
  },
  {
    tableName: 'organization',
    entityName: 'Organization',
    columns: [
      {
        entityName: 'organization',
        propertyName: 'id',
        columnName: 'id',
        attributeKey: 'PK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
      },
      {
        entityName: 'organization',
        propertyName: 'title',
        columnName: 'title',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
      },
      {
        entityName: 'organization',
        propertyName: 'description',
        columnName: 'description',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
      },
      {
        entityName: 'organization',
        propertyName: 'expire',
        columnName: 'expire',
        attributeKey: '',
        columnType: 'date',
        columnTypeWithLength: 'date',
        comment: '',
      },
    ],
  },
  {
    tableName: 'photo',
    entityName: 'Photo',
    columns: [
      {
        entityName: 'photo',
        propertyName: 'id',
        columnName: 'id',
        attributeKey: 'PK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
      },
      {
        entityName: 'photo',
        propertyName: 'title',
        columnName: 'title',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
      },
      {
        entityName: 'photo',
        propertyName: 'description',
        columnName: 'description',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
      },
      {
        entityName: 'photo',
        propertyName: 'size',
        columnName: 'size',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: '',
      },
    ],
  },
  {
    tableName: 'user',
    entityName: 'User',
    columns: [
      {
        entityName: 'user',
        propertyName: 'id',
        columnName: 'id',
        attributeKey: 'PK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
      },
      {
        entityName: 'user',
        propertyName: 'firstName',
        columnName: 'first_name',
        attributeKey: '',
        columnType: 'string',
        columnTypeWithLength: 'string',
        comment: 'user firstname',
      },
      {
        entityName: 'user',
        propertyName: 'lastName',
        columnName: 'lastName',
        attributeKey: '',
        columnType: 'varchar',
        columnTypeWithLength: 'varchar(64)',
        comment: '',
      },
      {
        entityName: 'user',
        propertyName: 'isActive',
        columnName: 'isActive',
        attributeKey: '',
        columnType: 'boolean',
        columnTypeWithLength: 'boolean',
        comment: 'line1<br />line2<br />line3',
      },
      {
        entityName: 'user',
        propertyName: 'photo',
        columnName: 'photoId',
        attributeKey: 'FK',
        columnType: 'number',
        columnTypeWithLength: 'number',
        comment: '',
      },
    ],
  },
];
