import { CE_TEMPLATE_NAME } from '#template/cosnt-enum/CE_TEMPLATE_NAME';

const htmlDocument = `<!DOCTYPE html>
<html lang="en">

<head>
  <% if (metadata.title != null) { %>
  <title><%= metadata.title %></title>
  <% } else { %>
  <title>ER diagram generated by erdia</title>
  <% } %>
  <meta charset="utf-8"> 
  <%- include('${CE_TEMPLATE_NAME.IMAGE_MERMAID_SCRIPT}', { entities, option, metadata }); %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  <%- include('${CE_TEMPLATE_NAME.IMAGE_STYLE}', { entities }); %>
</head>

<body class="bg-body-tertiary">
  <div class="bd-cheatsheet container-fluid bg-body">
    <section id="content">
      <h1 id="entity-relationship-mermiad-diagram" class="title is-3">
        <%= metadata.name %>
      </h1>

      <pre id="mermaid-diagram-container" class="mermaid">
        <%- include('${CE_TEMPLATE_NAME.MERMAID_DOCUMENT}', { entities, option, metadata }); %>
      </pre>
    </section>
  </div>
</body>

</html>`;

export default htmlDocument;
