import { CE_TEMPLATE_NAME } from '#template/cosnt-enum/CE_TEMPLATE_NAME';

const htmlDocument = `<!DOCTYPE html>
<html lang="en">

<head>
  <% if (it.metadata.title != null) { %>
  <title><%= it.metadata.title %></title>
  <% } else { %>
  <title>ER diagram generated by erdia</title>
  <% } %>
  <meta charset="utf-8"> 
  <%~ include('${CE_TEMPLATE_NAME.IMAGE_MERMAID_SCRIPT}', it); %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  <%~ include('${CE_TEMPLATE_NAME.IMAGE_STYLE}', it); %>
</head>

<body class="bg-body-tertiary">
  <div class="bd-cheatsheet container-fluid bg-body">
  <% it.versions.filter((version) => version.latest).forEach((version) => { %>
    <section id="content">
      <h1 id="entity-relationship-mermiad-diagram" class="title is-3">
        <%= it.metadata.name %>
      </h1>

      <pre id="mermaid-diagram-container" class="mermaid">
        <%~ include('${CE_TEMPLATE_NAME.MERMAID_DOCUMENT}', { entities: version.entities, option: it.option, metadata: it.metadata }); %>
      </pre>
    </section>
  <% }) %>
  </div>
</body>

</html>`;

export default htmlDocument;
