const template = `
<!DOCTYPE html>
<html lang="en">

<head>
  <title>ER diagram generated by erdia</title>

  <meta charset="utf-8">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css"
    integrity="sha512-IgmDkwzs96t4SrChW29No3NXBIBv8baW490zk5aXvhCD8vuZM3yUSkbyTBcXohkySecyzIrUwiF/qV0cuPcL3Q=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.14.0/mermaid.min.js"
    integrity="sha512-vLumCjg7NKEQKGM+xAgBYTvQ90DVu6Eo7vS1T/iPf2feNLcrpGxvumuUUmE3CPiCUPgviyKbtpWGDbhnVnmJxg=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>mermaid.initialize({startOnLoad:true});</script>
</head>

<body>
  $[##html-gernerated-table-replace-tag##]

  $[##html-gernerated-marmaid-replace-tag##]
</body>

</html>
`;

export default template;
